---
- name: 'Add or update user password'
  hosts: centos_clients

  tasks:
          - name: 'Change "george" password'
            user:
                    name: george
                    update_password: always
                    password: "{{ newpassword|password_hash('sha512') }}"
