---
- name: 'Copy file to remote clients'
  hosts: centos_clients
  vars:
          srcfile: /home/user/somefile
  tasks:
          - name: 'Copying file'
            become: true
            copy:
                    src: "{{ srcfile }}"
                    dest: /tpm
                    owner: user
                    group: user
                    mode: 0644

