---
- name: "Create Multiple Users in different hosts"
  hosts: centos_clients
  vars:
          users: [user1, user2, user3]

  tasks:
          - name: "Create Users"
            user:
                    name: '{{item}}'
            with_items: '{{users}}'
