---
- name: 'Create and mount new storage'
  hosts: localhost

  tasks:
          - name: 'Create new partition'
            parted:
                    name: files
                    label: gpt
                    device: /dev/vdb
                    number: 1
                    state: present
                    part_start: 1MiB
                    part_end: 4GiB

          - name: 'Create xfs filesystem'
            filesystem:
                    dev: /dev/vdb1
                    fstype: xfs

          - name: 'Create mount directory'
            file:
                    path: /data
                    state: directory

          - name: 'Mount the filesystem'
            mount:
                   src: /dev/vdb1
                   fstype: xfs
                   state: mounted
                   path: /data

