---
- name: 'Create a cron job'
  hosts: centos_clients

  tasks:
          - name: 'Schedule cron'
            cron:
                    name:  'The job is executed by ansible'
                    minute: "0"
                    hour: "10"
                    day: "*"
                    month: "*"
                    weekday: "4"
                    user: root
                    job: "/home/user/cfile.sh"  
