---
- name: "Install Apache Server"
  hosts: servers

  tasks:
          - name: "Install Apache on Debian"
            apt:
                    name: apache2
                    state: present
            when: ansible_os_family == "Debian"

          - name: "Install Apache on CentOS"
            yum:
                    name: httpd
                    state: present
            when: ansible_os_family == "RedHat"

