---
- name: "Update OS"
  hosts: centos_clients

  tasks:
          - name: "Updating OS"
            yum:
                    name: "*"
                    state: latest

          - name: "Check is a reboot is required"
            shell: needs-restarting -r
            failed_when: false
            changed_when: false
            register: reboot_required

          - name: "Reboot if required"
            reboot:
                    reboot_timeout: 300
            when: reboot_required == 1
